Mt-EB-Rainbow/front

src/api/Support.js
src/components/_common/Card/SiteCard.jsx
src/components/supportpage/Support.jsx

- 취업 지원 사이트 api를 연결하여 `siteType`에 따라 `SiteCard` 컴포넌트를 매핑했습니다.
- `SiteCard` 컴포넌트에서 기관명 글씨 색상이 #fff라서 흰 색 배경에서는 잘 보이지 않는다는 이슈가 있었습니다. 이를 해결하기 위해 기관명 뒷배경에 필터를 적용했습니다.
어떤 변경 사항이 있나요?

[hyebin] 취업 지원 사이트 api 연결

---

src/components/mainpage/Main.style.js
src/components/mainpage/MenuBtn.jsx
src/components/recommendpage/Recommend.jsx
src/components/recommendpage/Recommend.style.js

- 메인 페이지 메뉴 버튼 텍스트 줄바뀜 문제 해결
- 직무 추천 페이지 문항/답변 텍스트 색상 및 굵기 조절
어떤 변경 사항이 있나요?

[Hanby] 메인 페이지 및 직무 추천 페이지 css 수정

---

package-lock.json
package.json
src/components/resume/Modal.jsx
src/components/resume/New.jsx

[hyeonsu] 직무찾기 모달 퍼블리싱

---

src/components/resume/Modal.jsx

- 이력서 작성 페이지가 움직이지 않는 오류를 수정함
어떤 변경 사항이 있나요?

[hyeonsu] 모달 배경 오류 수정

---

src/api/dictionary.js
src/components/dictionarypage/Dictionary.jsx
src/components/dictionarypage/Dictionary.style.js
src/components/recommendpage/RecommendResult.jsx

- 직무 백과 api 연결을 완료했습니다.
- 직무 이름으로 검색할 수 있습니다 (결과 1개 이상).
- 카테고리/직무 이름을 선택하여 검색할 수 있습니다.
- 직무 추천에서 추천 직무백과 바로가기를 눌렀을 때 해당하는 직무가 노출됩니다. 
어떤 변경 사항이 있나요?

[Hanby] 직무 백과 api 연결

---

src/App.js
src/components/dictionarypage/Dictionary.jsx
src/components/dictionarypage/Dictionary.style.js
src/components/mainpage/Banner.jsx
src/components/recommendpage/Recommend.jsx
src/components/recommendpage/Recommend.style.js
src/components/recommendpage/RecommendResult.jsx
src/pages/RecommendResultPage.jsx

- 메인 페이지 배너 이미지를 추가했습니다.
- 직무 추천 결과 페이지를 /recommend/result로 분리했습니다.
- 직무 백과 입력 검증을 추가했습니다 (string의 경우 길이가 1 이상일 때만 활성화, 카테고리의 경우 두 분류가 모두 선택되어야 활성화) 
어떤 변경 사항이 있나요?

[Hanby] 직무 추천 결과 페이지 분리 및 직무 백과 입력 검증 추가

---

.prettierrc
jsconfig.json
src/components/childcarepage/Childcare.jsx
src/components/childcarepage/Childcare.style.js
src/components/childcarepage/NoTable.jsx
src/components/childcarepage/spin.css
src/components/mentorResume/CommentList.jsx
src/components/mentorResume/CommentWrite.jsx

보육 시설 로딩 추가, 
피드백 댓글 날짜 추가
어떤 변경 사항이 있나요?

[Hyeonsu] 보육 시설 로딩 추가, 피드백 댓글 날짜 추가

---

src/api/Signin.js
src/api/Signup.js
src/api/client.js
src/api/logout.js
src/components/_common/layout/NavBar.jsx
src/components/loginpage/LoginEmail.jsx
src/components/resume/Resume.style.js
src/components/signuppage/Signup02.jsx
src/components/signuppage/Signup02.style.js

로그아웃 구현
리프레시토큰 저장, 
로그인 상세 기능 구현 
- 네브바 로그인 -> 로그아웃으로 바꾸기
- 로그인, 회원가입 성공했을때만 넘어가도록
- 로그인 필드 수정
어떤 변경 사항이 있나요?

[Hyeonsu] 로그아웃 구현, 리프레시토큰 저장, 로그인 상세 기능 구현

---

src/App.js
src/api/Signup.js
src/api/isMentor.js
src/components/_common/layout/NavBar.jsx
src/components/signuppage/MentorSignup.jsx
src/components/signuppage/MentorSignup.style.js
src/components/signuppage/Signup01.jsx
src/components/signuppage/Signup02.jsx
src/components/signuppage/Signup02.style.js
src/recoil/loginState.js

멘토 로그인 추가
멘토인지 여부에 따라 이력서 파트 바뀌도록 수정
어떤 변경 사항이 있나요?

[Hyeonsu] 멘토 로그인 추가/ 네브바 수정

---

src/components/_common/layout/NavBar.jsx

- isMentor 여부를 잘 불러오지 못하는 이슈 수정 
어떤 변경 사항이 있나요?

[hyebin] navbar isMentor 여부에 따라 렌더링 다르게

---

src/components/mentorResume/GoLogin.jsx
src/pages/MentorBoardsPage.jsx

멘토 로그인 여부에 따른 이력서 피드백 접근제한
어떤 변경 사항이 있나요?

[Hyeonsu] 멘토 로그인 여부에 따른 이력서 피드백 접근제한

---

src/api/resume.js
src/components/resume/New.jsx
src/components/resume/Resume.jsx
src/util/DateFormatter.js

[hyebin] 이력서 디테일 get api 연결 완료

---

src/components/_common/layout/NavBar.jsx
src/components/resume/New.jsx

- 멘토인지 아닌지 반환하는 함수에 에러가 있어서 수정했습니다.
어떤 변경 사항이 있나요?

[hyebin] 멘토 상태 불러오기 버그 해결

---

src/components/_common/BoardsHeader.jsx
src/components/resume/New.jsx
src/components/resume/Resume.jsx

- 이력서 추가 버튼 위치 수정
어떤 변경 사항이 있나요?

fix: 이력서 추가 버튼 위치 수정

---

src/components/dictionarypage/Dictionary.jsx
src/components/dictionarypage/Dictionary.style.js

- 직무 설명 상세 내용들의 Label 이름을 수정했습니다.
- 직무 백과 Line의 잘못된 margin을 수정했습니다.
어떤 변경 사항이 있나요?

[Hanby] 직무 백과 Label 및 css 수정

---

src/api/isMentor.js
src/api/resume.js
src/components/resume/New.jsx

- navbar 멘토 상태 확인 버그 수정
- 이력서 정보 불러오기 버그 수정
어떤 변경 사항이 있나요?

[aoqlsdl] 버그 해결 

---

src/components/dictionarypage/Dictionary.jsx
src/components/dictionarypage/Dictionary.style.js
src/components/trainingpage/pagination.jsx

[Hyeonsu] 직무백과 여백 수정

---

src/api/isMentor.js
src/components/_common/layout/NavBar.jsx
src/components/mentorResume/MentorBoards.jsx
src/components/mentorResume/MentorFeedback.jsx
src/components/resume/New.style.js
src/components/resume/Resume.jsx
src/components/signuppage/MentorSignup.jsx
src/components/signuppage/Signup01.jsx
src/components/signuppage/Signup02.jsx
src/components/trainingpage/Training.jsx

[Hyeonsu] 피드백 날짜 변환

---

src/components/dictionarypage/Dictionary.style.js
src/components/trainingpage/Training.jsx
src/components/trainingpage/Training.style.js

- 검색 후 페이지네이션 누르면 원래 데이터로 돌아가는 문제 수정
- 검색 버튼 줄넘김 수정
어떤 변경 사항이 있나요?

[Hanby] 검색 관련 CSS 수정

---

src/components/trainingpage/Training.jsx

[hyeonsu]직업교육 페이지네이션 수정

---

src/components/trainingpage/Training.jsx
src/components/trainingpage/Training.style.js
src/components/trainingpage/pagination.jsx

[hyeonsu] 직무교육 페이지네이션 수정

---

src/components/resume/Modal.jsx
src/components/resume/New.jsx

직무 선택 모달 직무api, 직무 검색 api 연결
어떤 변경 사항이 있나요?

[hyeonsu] 직무 선택 모달 직무api, 직무 검색 api 연결

---

src/components/resume/Modal.jsx
src/components/resume/New.jsx

처음 모달 열 때 데이터 안 들어오는 문제 해결
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가

[hyeonsu] 처음 모달 열 때 데이터 안 들어오는 문제 해결

---

src/components/resume/New.jsx
src/components/resume/New.style.js

- 이력서 상세 직무 선택 버튼 및 입력 항목 정렬/줄바꿈 등의 문제를 해결했습니다.
어떤 변경 사항이 있나요?

[Hanby] 이력서 상세 css 수정 

---

src/api/resume.js
src/components/resume/New.jsx

- 이력서 api가 변경됨에 따라 새롭게 api를 연결하고 있습니다.
어떤 변경 사항이 있나요?

[hyebin] 이력서 post api 구현중

---

src/api/resume.js
src/components/resume/New.jsx
src/components/resume/New.style.js
src/components/resume/Resume.jsx
src/components/resume/Resume.style.js

- 이력서 목록 및 상세 페이지에 공개 여부/직무 선택도 api 연결했습니다.
- 이력서 목록 페이지의 이력서 삭제 api를 연결했습니다.
어떤 변경 사항이 있나요?

[Hanby] 이력서 등록 api 수정(공개 여부, 직무 선택 반영) 및 삭제 api 연결

---

src/api/resume.js
src/components/resume/New.jsx
src/util/DateFormatter.js

- 이력서 학력 전체 체크박스 중 하나만 체크되는 문제를 해결했습니다.
- 구직자 이력서 상세 학력/경력/어학/수상 및 기타 post, put, delete api를 연결했습니다. 
어떤 변경 사항이 있나요?

[Hanby] 구직자 이력서 상세 api 연결 완료
